import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { weekIsolationPlugin } from './week-isolation-plugin.js'
import { clearDayPlugin } from './clear-day-plugin.js'
import { enhancementSuitePlugin } from './enhancement-suite-plugin.js'
import { resetWeekScopePlugin } from './reset-week-scope-plugin.js'
import { shiftScopeCorePlugin } from './shift-scope-core-plugin.js'
import { laborShareCorePlugin } from './labor-share-core-plugin.js'
import { weekMetadataScopePlugin } from './week-metadata-scope-plugin.js'
import { shiftOpsLogicPlugin } from './shift-ops-logic-plugin.js'
import { shiftOpsSyntaxFixPlugin } from './shift-ops-syntax-fix-plugin.js'
import { laborShareComparisonPlugin } from './labor-share-comparison-plugin.js'
import { laborShareLogicPlugin } from './labor-share-logic-plugin.js'
import { speedLiteTeamsCorePlugin } from './speed-lite-teams-core-plugin.js'
import { speedLiteTeamsLogicPlugin } from './speed-lite-teams-logic-plugin.js'
import { speedLiteTeamsOrderPlugin } from './speed-lite-teams-order-plugin.js'
import { crossBoardAuditPlugin } from './cross-board-audit-plugin.js'
import { exportContextPlugin } from './export-context-plugin.js'
import { excelScopePlugin } from './excel-scope-plugin.js'
import { enhancementNavPlugin } from './enhancement-nav-plugin.js'
import { auditTabPlugin } from './audit-tab-plugin.js'
import { toolsTabPlugin } from './tools-tab-plugin.js'
import { speedLiteTeamsTemplatePlugin } from './speed-lite-teams-template-plugin.js'
import { shiftContextUxPlugin } from './shift-context-ux-plugin.js'
import { analysisScopePlugin } from './analysis-scope-plugin.js'
import { laborShareAreaAdminPlugin } from './labor-share-area-admin-plugin.js'
import { laborShareMovementPlugin } from './labor-share-movement-plugin.js'
import { speedLiteTeamsMovementPlugin } from './speed-lite-teams-movement-plugin.js'
import { laborShareBoardUiPlugin } from './labor-share-board-ui-plugin.js'
import { speedLiteTeamsUiPlugin } from './speed-lite-teams-ui-plugin.js'
import { laborShareAnalysisPlugin } from './labor-share-analysis-plugin.js'
import { speedLiteTeamsAnalysisPlugin } from './speed-lite-teams-analysis-plugin.js'
import { speedLiteTeamsAnalysisUiFixPlugin } from './speed-lite-teams-analysis-ui-fix-plugin.js'
import { laborShareSuggestionsPlugin } from './labor-share-suggestions-plugin.js'
import { speedLiteTeamsSuggestionsPlugin } from './speed-lite-teams-suggestions-plugin.js'
import { laborShareSlackPlugin } from './labor-share-slack-plugin.js'
import { speedLiteTeamsSlackPlugin } from './speed-lite-teams-slack-plugin.js'
import { managerTabPlugin } from './manager-tab-plugin.js'
import { speedLiteTeamsManagerPlugin } from './speed-lite-teams-manager-plugin.js'
import { suggestionsTabPlugin } from './suggestions-tab-plugin.js'
import { auditAdminPlugin } from './audit-admin-plugin.js'
import { auditActionsPlugin } from './audit-actions-plugin.js'
import { shiftCorePlugin } from './shift-core-plugin.js'
import { reportExportPlugin } from './report-export-plugin.js'
import { reportShiftFixPlugin } from './report-shift-fix-plugin.js'
import { laborShareExcelPlugin } from './labor-share-excel-plugin.js'
import { speedLiteTeamsExcelPlugin } from './speed-lite-teams-excel-plugin.js'
import { pdfDailyDataPlugin } from './pdf-daily-data-plugin.js'
import { pdfDailySectionPlugin } from './pdf-daily-section-plugin.js'
import { pdfWeeklyDataPlugin } from './pdf-weekly-data-plugin.js'
import { pdfWeeklySectionPlugin } from './pdf-weekly-section-plugin.js'
import { pdfFooterPlugin } from './pdf-footer-plugin.js'
import { laborSharePdfPlugin } from './labor-share-pdf-plugin.js'
import { speedLiteTeamsPdfPlugin } from './speed-lite-teams-pdf-plugin.js'
import { speedLiteTeamsValidationPlugin } from './speed-lite-teams-validation-plugin.js'
import { builderTagPlugin } from './builder-tag-plugin.js'
import { scheduledStatusPlugin } from './scheduled-status-plugin.js'

export default defineConfig({
  plugins: [weekIsolationPlugin(), clearDayPlugin(), enhancementSuitePlugin(), resetWeekScopePlugin(), shiftScopeCorePlugin(), laborShareCorePlugin(), weekMetadataScopePlugin(), shiftOpsLogicPlugin(), shiftOpsSyntaxFixPlugin(), laborShareComparisonPlugin(), laborShareLogicPlugin(), speedLiteTeamsCorePlugin(), speedLiteTeamsLogicPlugin(), speedLiteTeamsOrderPlugin(), crossBoardAuditPlugin(), exportContextPlugin(), excelScopePlugin(), enhancementNavPlugin(), auditTabPlugin(), toolsTabPlugin(), speedLiteTeamsTemplatePlugin(), shiftContextUxPlugin(), analysisScopePlugin(), laborShareAreaAdminPlugin(), laborShareMovementPlugin(), speedLiteTeamsMovementPlugin(), laborShareBoardUiPlugin(), speedLiteTeamsUiPlugin(), laborShareAnalysisPlugin(), speedLiteTeamsAnalysisPlugin(), speedLiteTeamsAnalysisUiFixPlugin(), laborShareSuggestionsPlugin(), speedLiteTeamsSuggestionsPlugin(), laborShareSlackPlugin(), speedLiteTeamsSlackPlugin(), managerTabPlugin(), speedLiteTeamsManagerPlugin(), suggestionsTabPlugin(), auditAdminPlugin(), auditActionsPlugin(), shiftCorePlugin(), reportExportPlugin(), reportShiftFixPlugin(), laborShareExcelPlugin(), speedLiteTeamsExcelPlugin(), pdfDailyDataPlugin(), pdfWeeklyDataPlugin(), pdfDailySectionPlugin(), pdfWeeklySectionPlugin(), pdfFooterPlugin(), laborSharePdfPlugin(), speedLiteTeamsPdfPlugin(), speedLiteTeamsValidationPlugin(), builderTagPlugin(), scheduledStatusPlugin(), react()],
  server: {
    host: '0.0.0.0',
    port: 5173,
    allowedHosts: ['squid-app-wrvn7.ondigitalocean.app', '.ondigitalocean.app', 'cloud-fronted.com'],
  },
})
